image:
  name: dotnet8_gitlab:latest
  pull_policy: if-not-present

stages:
  - build

build_backend:
  stage: build
  tags:
    - dotnet-core
  before_script:
    - dotnet restore
  script:
    - cd NatUp.Paco.API
    - echo "Build de l'application NatUp.Paco"
    - dotnet build -nowarn:CA1416

build_frontend:
  stage: build
  tags:
    - dotnet-core
  image: node20:latest
  cache:
    paths:
      - NatUp.Paco.Client/node_modules/
  script:
    - echo "Build de l'application NatUp.Paco.Client..."
    - cd NatUp.Paco.Client
    - npm ci
    - npm run build